default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: kaizen_flow_development

test:
  <<: *default
  database: kaizen_flow_test

production:
  primary: &primary_production
    <<: *default
    database: kaizen_flow_production
  cache:
    <<: *primary_production
    database: kaizen_flow_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: kaizen_flow_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: kaizen_flow_production_cable
    migrations_paths: db/cable_migrate
